# Generated by Django 5.1.5 on 2025-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('seasons', models.CharField(max_length=20)),
                ('crops', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
            ],
        ),
    ]
